name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      # - name: Print PATH
      #   run: echo $PATH
      - uses: actions/checkout@v2
        # with: actions/checkout
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Install ffmpeg (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install ffmpeg
      - name: Install ffmpeg (windows)
        if: matrix.os == 'windows-latest'
        run: choco install ffmpeg --version=6.1.0 --elevated
      # - name: List virtual environment contents
      #   run: ls -R $RUNNER_TOOL_CACHE/Python/*/x64/lib/python*/site-packages/
      - name: Test with tox
        run: tox
