name: tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Install ffmpeg (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install ffmpeg
      - name: Install ffmpeg (windows)
        if: matrix.os == 'windows-latest'
        run: choco install ffmpeg --version=5.1.1 --elevated
      - name: Test with tox
        run: tox

  artifact-inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python 3.11
        uses: actions/checkout@v4
        with:
          python-version: '3.11'
      - name: Download Scrivid
        run: 
          python -m pip install --upgrade pip
          pip install --editable git+https://github.com/TNTMaster370/scrivid.git#egg=scrivid --user
      - name: Run Python Script
        run: python -m tests/samples/notatruetest.py
      - name: Archive Directory
        run: tar czf directory-archive.tar.gz /scrivid/tests/samples/
        working-directory: ${{ github.workspace }}
      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: directory-artifact
          path: directory-archive.tar.gz
